### ISSUE TITLE
Segmentation fault when running on Linux

### ISSUE THREAD

**Issue by BrandonEdwards** [psolymos/wac2wav#2]
Appears to work fine on Windows 10, but when running on Linux machine (specifically running Ubuntu 20.04.5 LTS), I get a Segmentation Fault. I will investigate a bit further as to where in the code this segfault appears, and can suggest (or create) a fix if I find one.

**Comment by psolymos** [comment]
That would be appreciated. Thanks @BrandonEdwards !

**Comment by BrandonEdwards** [comment]
Hi Peter, realized that I haven't actually addressed this yet! Turns out that the seg fault was actually just Linux interpretation of special characters differing from Windows. Nothing to do with the wac2wav program at all! I'll close this issue.
